---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: DevOS DEMO VPC
        cidr_block: 10.15.0.0/16
        region: ap-northeast-1
        state: present
      register: vpc_result

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: ap-northeast-1
        state: present
        tags:
          Name: DevOS_DEMO_sydney_igw

    - name: Create Public Subnet
      ec2_vpc_subnet:
        cidr: 10.15.0.0/24
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: ap-northeast-1
        az: ap-southeast-2a
        map_public: yes
        state: present
      register: subnet_result

    - name: Create Security Group
      ec2_group:
        name: devos-demo-sg
        vpc_id: "{{ vpc_result.vpc.id }}"
        region: ap-northeast-1
        state: present
        description: allow 22, 80 devos-demo-sg 
        tags:
          Name: devos-demo-sg
        rules:
        - proto: tcp
          ports:
          - 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0

    - name: Create EC2
      ec2:
        key_name: sangyun-tokyo-keypair
        instance_tags:
          Name: devos-demo-ec2
        region: ap-northeast-1
        instance_type: t2.micro
        image: ami-0de5311b2a443fb89
        group: devos-demo-sg
        wait: yes
        count: 1
        vpc_subnet_id: "{{ subnet_result.subnet.id }}"
        assign_public_ip: yes
