---
- connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create EC2 Block
      amazon.aws.ec2_instance:
          region: ap-northeast-1
          key_name: sangyun-tokyo-keypair 
          group: devos-demo-sg
          instance_type: t2.micro
          image: ami-0de5311b2a443fb89
          wait: yes
          count: 1
          instance_tags:
            name: devos_ec2
            os: amazon_linux
          monitoring: no
          vpc_subnet_id: subnet-07e6775dad8f6950f
          assign_public_ip: yes
