---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Create EC2
      ec2:
        key_name: sangyun-tokyo-keypair
        instance_tags:
          Name: devos-demo-ec2
        region: ap-northeast-1
        instance_type: t2.micro
        image: ami-0de5311b2a443fb89
        group: devos-demo-sg
        wait: yes
        count: 1
        vpc_subnet_id: subnet-07e6775dad8f6950f
        assign_public_ip: yes
