---
- hosts: targetServer
  gather_facts: False
  become: true
  become_method: sudo
  
  tasks:
    - name: Host Info Facts
      command: "{{ command }}"
      register: host_info

    - name: Print Host Name
      debug:
        msg: "This hostName is   {{ host_info.stdout }}   "
    
    - name: update apt package
      shell: "apt-get update"
    
    - name: Enable nginx for ubuntu
      shell: "apt-get install -y nginx1.12"
      become: yes
